// app/all-products/dummyProductData.js

export const dummyProducts = [
  {
    id: 1,
    groupId: "toor-dal-1",
    visualId: "TOOR-DAL-1KG",
    name: "Toor Dal (Arhar)",
    weight: "1kg",
    price: 165,
    originalPrice: 195,
    discountedPrice: 140,
    discount: 15,
    rating: 4.7,
    reviews: 1284,
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=600&fit=crop&sat=-50",
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=600&fit=crop&sat=-100",
    ],
    category: "grains",
    badges: ["FSSAI Certified", "100% Natural"],
    inStock: true,
    countInStock: { quantity: 50 },
    mostSelling: true,
    description:
      "Premium quality Toor Dal (Arhar) sourced directly from Indian farms. Lab-tested for purity and authenticity.",
    nutritionalInfo: {
      protein: "22g",
      carbs: "57g",
      fiber: "15g",
      energy: "335kcal",
    },
    recipe: "Dal Tadka",
    variants: [
      { id: "500g", weight: "500g", price: 85, discountedPrice: 75 },
      { id: "1kg", weight: "1kg", price: 165, discountedPrice: 140 },
      { id: "5kg", weight: "5kg", price: 750, discountedPrice: 650 },
    ],
  },
  {
    id: 2,
    groupId: "moong-dal-1",
    visualId: "MOONG-DAL-1KG",
    name: "Moong Dal (Split)",
    weight: "1kg",
    price: 172,
    originalPrice: 195,
    discountedPrice: 148,
    discount: 12,
    rating: 4.6,
    reviews: 856,
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=600&fit=crop&sat=-100",
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=600&fit=crop&sat=-120",
    ],
    category: "grains",
    badges: ["FSSAI Certified", "100% Natural"],
    inStock: true,
    countInStock: { quantity: 35 },
    mostSelling: false,
    description:
      "Premium quality Split Moong Dal, perfect for khichdi and soups. Rich in protein and easy to digest.",
    nutritionalInfo: {
      protein: "24g",
      carbs: "59g",
      fiber: "16g",
      energy: "340kcal",
    },
    recipe: "Moong Dal Khichdi",
    variants: [
      { id: "500g", weight: "500g", price: 90, discountedPrice: 80 },
      { id: "1kg", weight: "1kg", price: 172, discountedPrice: 148 },
      { id: "5kg", weight: "5kg", price: 800, discountedPrice: 690 },
    ],
  },
  {
    id: 3,
    groupId: "sunflower-oil-1",
    visualId: "SUNFLOWER-OIL-1L",
    name: "Sunflower Cooking Oil",
    weight: "1L",
    price: 148,
    originalPrice: 175,
    discountedPrice: 128,
    discount: 15,
    rating: 4.5,
    reviews: 2340,
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop&sat=-50",
    ],
    category: "oils",
    badges: ["FSSAI Certified", "Heart Healthy"],
    inStock: true,
    countInStock: { quantity: 40 },
    mostSelling: true,
    description:
      "Pure sunflower cooking oil with high smoke point. Perfect for everyday cooking and deep frying.",
    nutritionalInfo: {
      protein: "0g",
      carbs: "0g",
      fiber: "0g",
      energy: "900kcal",
    },
    recipe: "Healthy Stir-fry",
    variants: [
      { id: "500ml", weight: "500ml", price: 78, discountedPrice: 68 },
      { id: "1L", weight: "1L", price: 148, discountedPrice: 128 },
      { id: "5L", weight: "5L", price: 700, discountedPrice: 620 },
    ],
  },
  {
    id: 4,
    groupId: "mustard-oil-1",
    visualId: "MUSTARD-OIL-1L",
    name: "Cold-Pressed Mustard Oil",
    weight: "1L",
    price: 210,
    originalPrice: 250,
    discountedPrice: 180,
    discount: 16,
    rating: 4.8,
    reviews: 1890,
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop&sat=-50",
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop&sat=-80",
    ],
    category: "oils",
    badges: ["Cold-Pressed", "100% Natural", "FSSAI Certified"],
    inStock: true,
    countInStock: { quantity: 25 },
    mostSelling: false,
    description:
      "Traditional cold-pressed mustard oil with strong pungent flavor. Rich in omega-3 fatty acids and antioxidants.",
    nutritionalInfo: {
      protein: "0g",
      carbs: "0g",
      fiber: "0g",
      energy: "902kcal",
    },
    recipe: "Fish Curry",
    variants: [
      { id: "500ml", weight: "500ml", price: 110, discountedPrice: 95 },
      { id: "1L", weight: "1L", price: 210, discountedPrice: 180 },
      { id: "5L", weight: "5L", price: 980, discountedPrice: 840 },
    ],
  },
  {
    id: 5,
    groupId: "turmeric-powder-1",
    visualId: "TURMERIC-POWDER-500G",
    name: "Organic Turmeric Powder",
    weight: "500g",
    price: 120,
    originalPrice: 150,
    discountedPrice: 120,
    discount: 0,
    rating: 4.9,
    reviews: 3420,
    images: [
      "https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=600&h=600&fit=crop&sat=-30",
    ],
    category: "spices",
    badges: ["Organic", "100% Natural", "FSSAI Certified"],
    inStock: true,
    countInStock: { quantity: 60 },
    mostSelling: true,
    description:
      "Pure organic turmeric powder with high curcumin content. Perfect for cooking and medicinal use.",
    nutritionalInfo: {
      protein: "8g",
      carbs: "65g",
      fiber: "21g",
      energy: "350kcal",
    },
    recipe: "Golden Turmeric Milk",
    variants: [
      { id: "250g", weight: "250g", price: 65, discountedPrice: 60 },
      { id: "500g", weight: "500g", price: 120, discountedPrice: 110 },
      { id: "1kg", weight: "1kg", price: 220, discountedPrice: 200 },
    ],
  },
  {
    id: 6,
    groupId: "red-chilli-powder-1",
    visualId: "RED-CHILLI-POWDER-500G",
    name: "Red Chilli Powder",
    weight: "500g",
    price: 95,
    originalPrice: 110,
    discountedPrice: 95,
    discount: 0,
    rating: 4.6,
    reviews: 2150,
    images: [
      "https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=600&h=600&fit=crop&sat=-60",
      "https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=600&h=600&fit=crop&sat=-80",
    ],
    category: "spices",
    badges: ["FSSAI Certified", "100% Natural"],
    inStock: true,
    countInStock: { quantity: 45 },
    mostSelling: false,
    description:
      "Premium quality red chilli powder with vibrant color and medium heat. Perfect for Indian curries.",
    nutritionalInfo: {
      protein: "15g",
      carbs: "56g",
      fiber: "30g",
      energy: "320kcal",
    },
    recipe: "Spicy Curry",
    variants: [
      { id: "250g", weight: "250g", price: 50, discountedPrice: 48 },
      { id: "500g", weight: "500g", price: 95, discountedPrice: 88 },
      { id: "1kg", weight: "1kg", price: 180, discountedPrice: 165 },
    ],
  },
  {
    id: 7,
    groupId: "cumin-seeds-1",
    visualId: "CUMIN-SEEDS-500G",
    name: "Cumin Seeds",
    weight: "500g",
    price: 85,
    originalPrice: 100,
    discountedPrice: 85,
    discount: 0,
    rating: 4.7,
    reviews: 1890,
    images: [
      "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&h=600&fit=crop&sat=-30",
    ],
    category: "spices",
    badges: ["FSSAI Certified", "100% Natural"],
    inStock: true,
    countInStock: { quantity: 55 },
    mostSelling: false,
    description:
      "Premium quality cumin seeds with strong aroma and flavor. Essential for Indian cooking.",
    nutritionalInfo: {
      protein: "18g",
      carbs: "44g",
      fiber: "10g",
      energy: "375kcal",
    },
    recipe: "Jeera Rice",
    variants: [
      { id: "250g", weight: "250g", price: 45, discountedPrice: 42 },
      { id: "500g", weight: "500g", price: 85, discountedPrice: 78 },
      { id: "1kg", weight: "1kg", price: 160, discountedPrice: 145 },
    ],
  },
  {
    id: 8,
    groupId: "coriander-powder-1",
    visualId: "CORIANDER-POWDER-500G",
    name: "Coriander Powder",
    weight: "500g",
    price: 90,
    originalPrice: 105,
    discountedPrice: 90,
    discount: 0,
    rating: 4.5,
    reviews: 1560,
    images: [
      "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&h=600&fit=crop&sat=-60",
      "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&h=600&fit=crop&sat=-80",
    ],
    category: "spices",
    badges: ["FSSAI Certified", "100% Natural"],
    inStock: true,
    countInStock: { quantity: 40 },
    mostSelling: false,
    description:
      "Pure coriander powder with mild, citrusy flavor. Essential for curries and spice blends.",
    nutritionalInfo: {
      protein: "12g",
      carbs: "54g",
      fiber: "42g",
      energy: "298kcal",
    },
    recipe: "Coriander Chutney",
    variants: [
      { id: "250g", weight: "250g", price: 48, discountedPrice: 45 },
      { id: "500g", weight: "500g", price: 90, discountedPrice: 82 },
      { id: "1kg", weight: "1kg", price: 170, discountedPrice: 155 },
    ],
  },
  {
    id: 9,
    groupId: "garam-masala-1",
    visualId: "GARAM-MASALA-250G",
    name: "Garam Masala",
    weight: "250g",
    price: 75,
    originalPrice: 90,
    discountedPrice: 75,
    discount: 0,
    rating: 4.8,
    reviews: 2100,
    images: [
      "https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=600&h=600&fit=crop&sat=-90",
      "https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=600&h=600&fit=crop&sat=-110",
    ],
    category: "spices",
    badges: ["FSSAI Certified", "100% Natural"],
    inStock: true,
    countInStock: { quantity: 30 },
    mostSelling: true,
    description:
      "Authentic garam masala blend made with premium spices. Adds warmth and depth to any dish.",
    nutritionalInfo: {
      protein: "14g",
      carbs: "50g",
      fiber: "28g",
      energy: "320kcal",
    },
    recipe: "Chicken Curry",
    variants: [
      { id: "100g", weight: "100g", price: 35, discountedPrice: 32 },
      { id: "250g", weight: "250g", price: 75, discountedPrice: 68 },
      { id: "500g", weight: "500g", price: 140, discountedPrice: 125 },
    ],
  },
  {
    id: 10,
    groupId: "black-pepper-1",
    visualId: "BLACK-PEPPER-500G",
    name: "Black Pepper",
    weight: "500g",
    price: 130,
    originalPrice: 155,
    discountedPrice: 130,
    discount: 0,
    rating: 4.9,
    reviews: 2780,
    images: [
      "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&h=600&fit=crop&sat=-100",
      "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&h=600&fit=crop&sat=-120",
    ],
    category: "spices",
    badges: ["FSSAI Certified", "100% Natural"],
    inStock: true,
    countInStock: { quantity: 35 },
    mostSelling: false,
    description:
      "Premium black pepper with strong aroma and sharp flavor. Known as the king of spices.",
    nutritionalInfo: {
      protein: "11g",
      carbs: "64g",
      fiber: "26g",
      energy: "251kcal",
    },
    recipe: "Pepper Lemonade",
    variants: [
      { id: "250g", weight: "250g", price: 68, discountedPrice: 62 },
      { id: "500g", weight: "500g", price: 130, discountedPrice: 118 },
      { id: "1kg", weight: "1kg", price: 250, discountedPrice: 225 },
    ],
  },
  {
    id: 11,
    groupId: "pink-salt-1",
    visualId: "PINK-SALT-1KG",
    name: "Himalayan Pink Salt",
    weight: "1kg",
    price: 120,
    originalPrice: 140,
    discountedPrice: 120,
    discount: 0,
    rating: 4.6,
    reviews: 1900,
    images: [
      "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=600&fit=crop&sat=-30",
    ],
    category: "spices",
    badges: ["100% Natural", "Rich in Minerals"],
    inStock: true,
    countInStock: { quantity: 50 },
    mostSelling: false,
    description:
      "Pure Himalayan pink salt with 84 trace minerals. Perfect for cooking and finishing dishes.",
    nutritionalInfo: {
      protein: "0g",
      carbs: "0g",
      fiber: "0g",
      energy: "0kcal",
    },
    recipe: "Salt Crust Chicken",
    variants: [
      { id: "500g", weight: "500g", price: 65, discountedPrice: 60 },
      { id: "1kg", weight: "1kg", price: 120, discountedPrice: 110 },
      { id: "5kg", weight: "5kg", price: 550, discountedPrice: 500 },
    ],
  },
  {
    id: 12,
    groupId: "sugar-white-1",
    visualId: "SUGAR-WHITE-1KG",
    name: "Sugar (White)",
    weight: "1kg",
    price: 55,
    originalPrice: 65,
    discountedPrice: 55,
    discount: 0,
    rating: 4.3,
    reviews: 1200,
    images: [
      "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=600&fit=crop&sat=-50",
      "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=600&fit=crop&sat=-70",
    ],
    category: "grains",
    badges: ["FSSAI Certified"],
    inStock: true,
    countInStock: { quantity: 100 },
    mostSelling: true,
    description:
      "Fine quality white sugar. Perfect for baking, cooking, and sweetening beverages.",
    nutritionalInfo: {
      protein: "0g",
      carbs: "100g",
      fiber: "0g",
      energy: "387kcal",
    },
    recipe: "Classic Lemonade",
    variants: [
      { id: "500g", weight: "500g", price: 30, discountedPrice: 28 },
      { id: "1kg", weight: "1kg", price: 55, discountedPrice: 50 },
      { id: "5kg", weight: "5kg", price: 250, discountedPrice: 225 },
    ],
  },
  {
    id: 13,
    groupId: "brown-sugar-1",
    visualId: "BROWN-SUGAR-1KG",
    name: "Brown Sugar",
    weight: "1kg",
    price: 75,
    originalPrice: 90,
    discountedPrice: 75,
    discount: 0,
    rating: 4.5,
    reviews: 980,
    images: [
      "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=600&fit=crop&sat=-90",
      "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=600&fit=crop&sat=-110",
    ],
    category: "grains",
    badges: ["100% Natural", "Less Processed"],
    inStock: true,
    countInStock: { quantity: 40 },
    mostSelling: false,
    description:
      "Natural brown sugar with rich molasses flavor. Perfect for baking and caramelizing.",
    nutritionalInfo: {
      protein: "0g",
      carbs: "98g",
      fiber: "0g",
      energy: "380kcal",
    },
    recipe: "Brown Sugar Cookies",
    variants: [
      { id: "500g", weight: "500g", price: 40, discountedPrice: 38 },
      { id: "1kg", weight: "1kg", price: 75, discountedPrice: 68 },
      { id: "5kg", weight: "5kg", price: 350, discountedPrice: 315 },
    ],
  },
  {
    id: 14,
    groupId: "desi-ghee-1",
    visualId: "DESI-GHEE-1L",
    name: "Desi Ghee",
    weight: "1L",
    price: 450,
    originalPrice: 500,
    discountedPrice: 450,
    discount: 0,
    rating: 4.9,
    reviews: 3200,
    images: [
      "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&h=600&fit=crop&sat=-130",
      "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&h=600&fit=crop&sat=-150",
    ],
    category: "oils",
    badges: ["Pure", "Traditional"],
    inStock: true,
    countInStock: { quantity: 20 },
    mostSelling: true,
    description:
      "Pure desi ghee made from traditional bilona method. Rich in healthy fats and nutrients.",
    nutritionalInfo: {
      protein: "0g",
      carbs: "0g",
      fiber: "0g",
      energy: "900kcal",
    },
    recipe: "Ghee Rice",
    variants: [
      { id: "500ml", weight: "500ml", price: 230, discountedPrice: 210 },
      { id: "1L", weight: "1L", price: 450, discountedPrice: 410 },
      { id: "5L", weight: "5L", price: 2150, discountedPrice: 1950 },
    ],
  },
  {
    id: 15,
    groupId: "peanut-oil-1",
    visualId: "PEANUT-OIL-1L",
    name: "Peanut Oil",
    weight: "1L",
    price: 160,
    originalPrice: 185,
    discountedPrice: 160,
    discount: 0,
    rating: 4.4,
    reviews: 1450,
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop&sat=-100",
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop&sat=-120",
    ],
    category: "oils",
    badges: ["100% Natural", "FSSAI Certified"],
    inStock: true,
    countInStock: { quantity: 35 },
    mostSelling: false,
    description:
      "Pure peanut oil with high smoke point. Perfect for deep frying and Asian cooking.",
    nutritionalInfo: {
      protein: "0g",
      carbs: "0g",
      fiber: "0g",
      energy: "884kcal",
    },
    recipe: "Schezwan Noodles",
    variants: [
      { id: "500ml", weight: "500ml", price: 85, discountedPrice: 78 },
      { id: "1L", weight: "1L", price: 160, discountedPrice: 145 },
      { id: "5L", weight: "5L", price: 750, discountedPrice: 680 },
    ],
  },
  {
    id: 16,
    groupId: "sesame-oil-1",
    visualId: "SESAME-OIL-1L",
    name: "Sesame Oil",
    weight: "1L",
    price: 190,
    originalPrice: 220,
    discountedPrice: 190,
    discount: 0,
    rating: 4.7,
    reviews: 1650,
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop&sat=-130",
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop&sat=-150",
    ],
    category: "oils",
    badges: ["Cold-Pressed", "100% Natural"],
    inStock: true,
    countInStock: { quantity: 28 },
    mostSelling: false,
    description:
      "Traditional cold-pressed sesame oil with rich nutty flavor. Great for Asian cuisine and Ayurveda.",
    nutritionalInfo: {
      protein: "0g",
      carbs: "0g",
      fiber: "0g",
      energy: "884kcal",
    },
    recipe: "Sesame Chicken",
    variants: [
      { id: "500ml", weight: "500ml", price: 100, discountedPrice: 92 },
      { id: "1L", weight: "1L", price: 190, discountedPrice: 172 },
      { id: "5L", weight: "5L", price: 890, discountedPrice: 800 },
    ],
  },
  {
    id: 17,
    groupId: "coconut-oil-1",
    visualId: "COCONUT-OIL-1L",
    name: "Coconut Oil",
    weight: "1L",
    price: 250,
    originalPrice: 280,
    discountedPrice: 250,
    discount: 0,
    rating: 4.8,
    reviews: 2800,
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop&sat=-160",
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop&sat=-180",
    ],
    category: "oils",
    badges: ["Virgin", "Cold-Pressed", "100% Natural"],
    inStock: true,
    countInStock: { quantity: 30 },
    mostSelling: true,
    description:
      "Pure virgin coconut oil with natural coconut aroma. Great for cooking, skincare, and hair care.",
    nutritionalInfo: {
      protein: "0g",
      carbs: "0g",
      fiber: "0g",
      energy: "862kcal",
    },
    recipe: "Coconut Curry",
    variants: [
      { id: "500ml", weight: "500ml", price: 135, discountedPrice: 122 },
      { id: "1L", weight: "1L", price: 250, discountedPrice: 225 },
      { id: "5L", weight: "5L", price: 1150, discountedPrice: 1035 },
    ],
  },
  {
    id: 18,
    groupId: "basmati-rice-1",
    visualId: "BASMATI-RICE-1KG",
    name: "Basmati Rice",
    weight: "1kg",
    price: 180,
    originalPrice: 210,
    discountedPrice: 180,
    discount: 0,
    rating: 4.9,
    reviews: 3500,
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=600&fit=crop&sat=-150",
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=600&fit=crop&sat=-170",
    ],
    category: "grains",
    badges: ["Premium", "Aged", "FSSAI Certified"],
    inStock: true,
    countInStock: { quantity: 60 },
    mostSelling: true,
    description:
      "Premium aged basmati rice with long grains and aromatic flavor. Perfect for biryani and pulao.",
    nutritionalInfo: {
      protein: "8g",
      carbs: "79g",
      fiber: "1g",
      energy: "350kcal",
    },
    recipe: "Chicken Biryani",
    variants: [
      { id: "500g", weight: "500g", price: 95, discountedPrice: 88 },
      { id: "1kg", weight: "1kg", price: 180, discountedPrice: 165 },
      { id: "5kg", weight: "5kg", price: 850, discountedPrice: 780 },
    ],
  },
  {
    id: 19,
    groupId: "wheat-flour-1",
    visualId: "WHEAT-FLOUR-1KG",
    name: "Wheat Flour",
    weight: "1kg",
    price: 65,
    originalPrice: 75,
    discountedPrice: 65,
    discount: 0,
    rating: 4.4,
    reviews: 1100,
    images: [
      "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=600&fit=crop&sat=-140",
      "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=600&fit=crop&sat=-160",
    ],
    category: "grains",
    badges: ["100% Whole Wheat", "FSSAI Certified"],
    inStock: true,
    countInStock: { quantity: 80 },
    mostSelling: true,
    description:
      "Premium whole wheat flour ground from select wheat. Perfect for daily bread making.",
    nutritionalInfo: {
      protein: "12g",
      carbs: "72g",
      fiber: "12g",
      energy: "340kcal",
    },
    recipe: "Whole Wheat Roti",
    variants: [
      { id: "500g", weight: "500g", price: 35, discountedPrice: 32 },
      { id: "1kg", weight: "1kg", price: 65, discountedPrice: 60 },
      { id: "5kg", weight: "5kg", price: 300, discountedPrice: 270 },
    ],
  },
  {
    id: 20,
    groupId: "besan-1",
    visualId: "BESAN-1KG",
    name: "Besan (Gram Flour)",
    weight: "1kg",
    price: 95,
    originalPrice: 110,
    discountedPrice: 95,
    discount: 0,
    rating: 4.6,
    reviews: 1580,
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=600&fit=crop&sat=-190",
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=600&fit=crop&sat=-210",
    ],
    category: "grains",
    badges: ["100% Natural", "High Protein", "FSSAI Certified"],
    inStock: true,
    countInStock: { quantity: 45 },
    mostSelling: false,
    description:
      "Pure besan (gram flour) made from roasted chickpeas. Essential for Indian snacks and sweets.",
    nutritionalInfo: {
      protein: "22g",
      carbs: "57g",
      fiber: "10g",
      energy: "387kcal",
    },
    recipe: "Besan Ladoo",
    variants: [
      { id: "500g", weight: "500g", price: 50, discountedPrice: 46 },
      { id: "1kg", weight: "1kg", price: 95, discountedPrice: 88 },
      { id: "5kg", weight: "5kg", price: 440, discountedPrice: 400 },
    ],
  },
];

// Export first product as default for single product views
export const dummyProduct = dummyProducts[0];

// Helper function to get product by groupId
export const getProductByGroupId = (groupId) => {
  return dummyProducts.find((product) => product.groupId === groupId);
};

// Helper function to get product by id
export const getProductById = (id) => {
  return dummyProducts.find((product) => product.id === id);
};

// Helper function to get products by category
export const getProductsByCategory = (category) => {
  return dummyProducts.filter((product) => product.category === category);
};

// Helper function to get most selling products
export const getMostSellingProducts = () => {
  return dummyProducts.filter((product) => product.mostSelling);
};
